version: '1.0'
name: pipeline-20251228
displayName: 自动部署文档站点
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
    paths:
      precise:
        - docs/site
stages:
  - name: stage-85fc9c58
    displayName: 部署文档站点
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: execute@docker
        name: execute_by_docker
        displayName: 基于镜像的脚本执行
        certificate: ''
        image: ubuntu
        command:
          - '# 请在此输入您想执行的脚本'
          - echo 'Hello Gitee!'
        notify: []
        strategy:
          retry: '0'
